version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - my-overlay-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  my-overlay-network:
    driver: overlay
    attachable: true
