FROM node:18.15 AS node-base
WORKDIR /backend


COPY backend/package*.json ./
RUN npm install && npm cache clean --force

COPY backend/ ./

FROM python:3.9 AS python-base
WORKDIR /scrapers

COPY scrapers/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY scrapers/ ./

FROM node:18.15 AS final
WORKDIR /backend

RUN groupadd -r appuser && useradd -r -g appuser -m appuser

USER appuser

COPY --from=node-base /backend /backend
COPY --from=python-base /scrapers /scrapers

ENV PATH="/backend/node_modules/.bin:$PATH"

COPY env.sh /backend/env.sh

RUN chmod +x /backend/env.sh

EXPOSE 5000

CMD ["./env.sh"]
