FROM node:18.15 AS node-base
WORKDIR /backend

COPY backend/package*.json ./
RUN npm install && npm cache clean --force

COPY backend/ ./

FROM python:3.9 AS python-base
WORKDIR /scrapers

COPY scrapers/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY scrapers/ ./

FROM node:18.15 AS final
WORKDIR /backend

RUN groupadd -r appuser && useradd -r -g appuser -m appuser

USER appuser

COPY --from=node-base /backend /backend
COPY --from=python-base /scrapers /scrapers

ENV STEAM_API_KEY=/run/secrets/STEAM_API_KEY
ENV TWITCH_API_KEY=/run/secrets/TWITCH_API_KEY
ENV TWITCH_CLIENT_KEY=/run/secrets/TWITCH_CLIENT_KEY
ENV FRONTEND_URL=/run/secrets/FRONTEND_URL
ENV BACKEND_URL=/run/secrets/BACKEND_URL
ENV OPENAI_API_KEY=/run/secrets/OPENAI_API_KEY
ENV MONGO_DB=/run/secrets/MONGO_DB
ENV SESSION_SECRET=/run/secrets/SESSION_SECRET
ENV AUTHORITY=/run/secrets/AUTHORITY
ENV CLIENT_ID=/run/secrets/CLIENT_ID
ENV REDIRECT_URL=/run/secrets/REDIRECT_URL
ENV RESPONSE_TYPE=/run/secrets/RESPONSE_TYPE
ENV LOGOUT_URL=/run/secrets/LOGOUT_URL
ENV SCOPE=/run/secrets/SCOPE

ENV PATH="/backend/node_modules/.bin:$PATH"

EXPOSE 5000

CMD ["npm", "start"]
