version: "3.7"

services:
  frontend:
    container_name: frontend
    image: frontend-image:latest
    secrets:
      - VITE_BACKEND_URL
    networks:
      - my-network
    expose:
      - "80" 

secrets:
  VITE_BACKEND_URL:
    external: true

networks:
  my-network:
    external: true
