FROM node:16 as builder

WORKDIR /frontend

COPY ./frontend/package*.json ./

RUN npm install

COPY frontend/ ./

ARG VITE_BACKEND_URL

RUN VITE_BACKEND_URL=$VITE_BACKEND_URL npm run build 

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /frontend/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]