FROM node:16 as builder

WORKDIR /frontend

COPY ./frontend/package*.json ./

RUN npm install

COPY frontend/ ./

ARG VITE_BACKEND_URL

RUN echo "VITE_BACKEND_URL=$VITE_BACKEND_URL" && \
    npm run build

FROM nginx:alpine

RUN adduser -D -u 1001 -g 1001 frontend

RUN rm /etc/nginx/conf.d/default.conf

RUN chown -R frontend:frontend /usr/share/nginx/html /etc/nginx
RUN chown -R frontend:frontend /var/cache/nginx
RUN touch /var/run/nginx.pid && chown frontend:frontend /var/run/nginx.pid

COPY --from=builder /frontend/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

USER frontend

CMD ["nginx", "-g", "daemon off;"]